# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.4.8

pipelines:
  default:
    - step:
        name: deployement
        script:
          - pipe: atlassian/ssh-run:0.2.6
            variables:
              SSH_USER: 'root'
              SERVER: '139.59.158.70'
              MODE: 'command'
              COMMAND: './deployApi.sh'
